### ISSUE TITLE
Suggestion:  use library dependencies from local repository (~/.m2/repository) as preferred alternative to `.library-dependencies`

### ISSUE THREAD

**Issue by scottkurz** [IBM/codenet-minerva-code-analyzer#33]
Copying dependencies to `.library-dependencies` takes up space and now requires an extra .gitignore or possible clean action.

Since this tool is already Maven-aware could it simply build whatever "classpath" it's using this directory for and point to the JARs in the local ~/.m2/repository.  This may require some piece of the Maven lifecycle to have run to download those deps but this is probably already happening.

**Comment by sinha108** [comment]
@scottkurz: The `.library-dependencies` directory is now removed at the end of the analysis run, so it exists only temporarily while the analysis is running (also the directory has been renamed to `_library_dependencies`; this should avoid the space/clenaup issues you mentioned.

**Comment by scottkurz** [comment]
Running into issues (probably permissions) on Windows..opened https://github.com/IBM/codenet-minerva-code-analyzer/issues/74
